# This is a basic workflow that is manually triggered

name: Notify_subscribers

# Controls when the action will run. Using workflow_dispatch runs when manually triggered using the UI
# or API.
on:
  # # This will not work for drafted PRs
  release:
    types: [published, edited, released]
  workflow_dispatch:
    inputs:
      tags:
        description: Tag to send notification about
        required: false
        type: string

permissions:
  # This permission is needed so that git tags can be created.
  contents: write
  # This permission is needed for OIDC based publishing.
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      # - name: print GH events object
      #   run:  |
      #     echo -e "GITHUB OBJECT: ${{ toJSON(github) }}\n\n"
      #     echo -e "====END======== \n \n \n"
      - name: Get Latest Release URL
        id: get_url
        run: |
          URL=$(gh release view --repo ${{github.repository}} --json url)
          echo "RELEASE_URL=$URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set latest release url
        id: set_RELEASE_NAME
        # github.event.workflow_run.head_branch will be the tag used when
        # running the create_release.yml workflow.
        if: github.ref == 'refs/tags/*'
        run:  |
            echo "LATEST_RELEASE_URL=https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}}" >> "$GITHUB_ENV"
      # - name: set latest release url with workflow_run
      #   id: set_RELEASE_NAME_with_workflow_run
        # github.event.workflow_run.head_branch will be the tag used when
        # running the create_release.yml workflow.
        # if: github.ref == ''
        # run:  |
        #     echo "LATEST_RELEASE_URL=https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}}" >> "$GITHUB_ENV"


      - name: Gets Release Name
        id: get_RELEASE_NAME
        run: |
          echo "LATEST_RELEASE_URL is '$LATEST_RELEASE_URL'"

      - name: Notify Slack Channel
        id: notify
        run: |

          # Debug workflow without actually notifying
          echo -e "release name inits to... ${{steps.get_url.outputs.RELEASE_URL}}"
          echo -e "is release name set? $LATEST_RELEASE_URL"
    #   run: |
    #      curl -X POST -H 'Content-type: application/json' \
    #      --data '{"text": ":::TESTING PLEASE IGNORE::: The Android mobile agent has created a new release candidate $LATEST_RELEASE_URL"}' \
    #      'https://hooks.slack.com/services/${{secrets.SLACK_WEBHOOK_TOKEN}}'
