# This is a basic workflow that is manually triggered

name: Notify_subscribers


# Controls when the action will run. Using workflow_dispatch runs when manually triggered using the UI
# or API.
on:
  # # This will not work for drafted PRs
  release:
    types: [created, published, edited, released]
  workflow_dispatch:
    inputs:
      debug:
        description: flag to set debug
        default: false
        required: false
        type: boolean
      tags:
        description: Tag to send notification about
        required: false
        type: string

permissions:
  # This permission is needed so that git tags can be created.
  contents: write
  # This permission is needed for OIDC based publishing.
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release URL
        id: get_url
        run: |
          URL=$(gh release view --repo ${{github.repository}} --json url)
          echo "RELEASE_URL=$URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: DEBUG Notify Slack Channel
        id: debug_notify
        if: ${{inputs.debug == true}}
        run: echo -e "release name inits to... ${{steps.get_url.outputs.RELEASE_URL}}"
      - name: DEBUG Notify Slack Channel
        id: notify
        if: ${{inputs.debug == false}}
        run: echo -e "The Android mobile agent team has released a new version of the agent ${{steps.get_url.outputs.RELEASE_URL.url}}"
    # change `run` to the below `run`
    #   run: |
    #      curl -X POST -H 'Content-type: application/json' \
    #      --data '{"text": "The Android mobile agent team has released a new version of the agent ${{steps.get_url.outputs.RELEASE_URL}}"}' \S
    #      'https://hooks.slack.com/services/${{secrets.SLACK_WEBHOOK_TOKEN}}'
