# This is a basic workflow that is manually triggered

name: Notify_subscribers

# Controls when the action will run. Using workflow_dispatch runs when manually triggered using the UI
# or API.
on:
  # # This will not work for drafted PRs
  # release:
  #   types: ['created']

  workflow_run:
    workflows: ['Release']
    types: ['completed']

    # workflow_dispatch:
  #   # Inputs the workflow accepts.
  #   inputs:
  #     name:
  #       # Friendly description to be shown in the UI instead of 'name'
  #       description: 'Notify mobile agent subscribers'

permissions:
  # This permission is needed so that git tags can be created.
  contents: write
  # This permission is needed for OIDC based publishing.
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: print GH events object
        run:  |
          echo -e "GITHUB OBJECT: ${{ toJSON(github) }}\n\n"
          echo -e "====END======== \n \n \n"
      - name: Print latest release url
        id: set_RELEASE_NAME
        run:  |
          # echo "LATEST_RELEASE_URL=https://github.com/${{github.repository}}/releases/tag/${{github.event.workflow_run.head_branch}}" >> "$GITHUB_ENV"
          echo RELEASE_URL="${{github.event.workflow_run.repository.releases_url}} | sed -E "s/{\/id}/'${{github.event.workflow_run.head_branch}}'/" >> "$GITHUB_ENV"


      - name: Notify Slack Channel
        id: notify
        run: |
          echo -e "is release name set? $RELEASE_URL"
    #   run: |
    #      curl -X POST -H 'Content-type: application/json' \
    #      --data '{"text": ":::TESTING PLEASE IGNORE::: The Android mobile agent has created a new release candidate ${{github.events.workflow_run.html_url}}"}' \
    #      'https://hooks.slack.com/services/${{secrets.SLACK_WEBHOOK_TOKEN}}'
